### ISSUE TITLE
Plugin Not Syncing All images on website

### ISSUE THREAD

**Issue by cliftonc0613** [junaidbhura/auto-cloudinary#11]
Hi @junaidbhura,

I just starting using your plugin like 2 or 3 days ago. It has synced some of the image(62) but I have over 4,000 images on my e-commerce website ([https://mrknickerbocker.com/home/](https://mrknickerbocker.com/home/)). I am using [Elementor](https://elementor.com/) and the [Astra Pro Theme](https://wpastra.com/) I have gone through the setting and set it up as it says on the wiki. What am I missing? Below is a screenshot of my settings.

![screen shot 2018-10-19 at 9 01 22 am](https://user-images.githubusercontent.com/1175246/47219792-d4d67f80-d37d-11e8-86f8-5b19fc80f383.png)

**Comment by junaidbhura** [comment]
Hey @cliftonc0613 looks like your theme has a lot of "background-images". This plugin can only work with replacing IMG tags. So unfortunately, this plugin is not compatible with your theme out of the box.

You can take a look at the documentation to see how you can edit your theme to take advantage of this plugin:

https://github.com/junaidbhura/auto-cloudinary/wiki/Functions
https://github.com/junaidbhura/auto-cloudinary/wiki/Filters

**Comment by cliftonc0613** [comment]
Thank you so much! I really appreciate it. Love your plugin

**Comment by junaidbhura** [comment]
No worries @cliftonc0613 cheers!
