### ISSUE TITLE
If ajax request, the plug-in cannot initialize

### ISSUE THREAD

**Issue by baronleung** [junaidbhura/auto-cloudinary#13]
if ( is_admin() ) {
                // if use admin-ajax.php, run this
		// Admin stuff
		Admin::get_instance()->setup();
	} else {
		// Front-end stuff.
		Core::get_instance()->setup();
		Frontend::get_instance()->setup();
	}

**Comment by junaidbhura** [comment]
Hey @baronleung thanks for the issue. Can you provide more details about what kind of AJAX call are you trying to make? Is it an authenticated or unauthenticated AJAX call?

What are you trying to achieve? Can you add some code samples so I can better understand this issue?

**Comment by baronleung** [comment]
@junaidbhura  sorry, my english is poor. hope you can understand what I mean.

// test plugin
|auto-cloudinary-ajax-test
|- auto-cloudinary-ajax-test.php
|- js/test.js

auto-cloudinary-ajax-test.php
----------------------------------------------------------------------------------------------------------------
<?php
/*
Plugin Name: Auto Cloudinary Ajax Test
Description: test ajax
Version: 1.0
Author: Baron Leung
Author URI: http://localhost
Text Domain: cloudinary ajax test
*/

add_action('wp_ajax_nopriv_cloudinary_test', 'cloudinary_ajax_test');
add_action('wp_ajax_cloudinary_test',             'cloudinary_ajax_test');
add_action('init',                                               'cloudinary_ajax_test_load_script');

if (!function_exists('cloudinary_ajax_test_load_script')) {
    function cloudinary_ajax_test_load_script() {
        wp_enqueue_script(
            'cloudinary_ajax_test',
            plugin_dir_url(__FILE__). 'js/test.js',
            array('jquery')
        );

        wp_localize_script(
            'cloudinary_ajax_test',
            'cloudinary_ajax_test',
            array('ajax_url' => admin_url('admin-ajax.php'))
        );
    }
}

if(!function_exists('cloudinary_ajax_test')) {
    function cloudinary_ajax_test() {

        // load template code
        // use a simple alternative here
        wp_send_json(array(
            // check issue
            // try modify the return value of cloudinary_update_content_images()
            // return JB\Cloudinary\Core::get_instance();

            // @see namespace.php
            // It does not initialize JB\Cloudinary\Core::get_instance()->setup(), 
            // but initializes JB\Cloudinary\Admin::get_instance()->setup()

            'html' => cloudinary_update_content_images('<img class="wp-image-123" src="http:://localhost/test.jpg">')
        ));

        wp_die();
    }
}


js/test.js
-------------------------------------------------------------------------------------------------------------
(function ($) {
    var test_url;

    if(typeof ajaxurl === "undefined") {
        test_url = cloudinary_ajax_test.ajax_url;
    } else {
        test_url = ajaxurl;
    }

    $.get(test_url, {action: "cloudinary_test"}, function (res) {
        console.log(res.html);
    });

})(jQuery);

**Comment by baronleung** [comment]
@junaidbhura test code I have sent to info@junaidbhura.com

**Comment by baronleung** [comment]
@junaidbhura  sorry, my english is poor. hope you can understand what I
mean.

// test plugin
|auto-cloudinary-ajax-test
|- auto-cloudinary-ajax-test.php
|- js/test.js

auto-cloudinary-ajax-test.php
----------------------------------------------------------------------------------------------------------------
<?php
/*
Plugin Name: Auto Cloudinary Ajax Test
Description: test ajax
Version: 1.0
Author: Baron Leung
Author URI: http://localhost
Text Domain: cloudinary ajax test
*/

add_action('wp_ajax_nopriv_cloudinary_test', 'cloudinary_ajax_test');
add_action('wp_ajax_cloudinary_test',             'cloudinary_ajax_test');
add_action('init',
'cloudinary_ajax_test_load_script');

if (!function_exists('cloudinary_ajax_test_load_script')) {
    function cloudinary_ajax_test_load_script() {
        wp_enqueue_script(
            'cloudinary_ajax_test',
            plugin_dir_url(__FILE__). 'js/test.js',
            array('jquery')
        );

        wp_localize_script(
            'cloudinary_ajax_test',
            'cloudinary_ajax_test',
            array('ajax_url' => admin_url('admin-ajax.php'))
        );
    }
}

if(!function_exists('cloudinary_ajax_test')) {
    function cloudinary_ajax_test() {

        // load template code
        // use a simple alternative here
        wp_send_json(array(
            // check issue
            // try modify the return value of
cloudinary_update_content_images()
            // return JB\Cloudinary\Core::get_instance();

            // @see namespace.php
            // It does not initialize
JB\Cloudinary\Core::get_instance()->setup(),
            // but initializes JB\Cloudinary\Admin::get_instance()->setup()

            'html' => cloudinary_update_content_images('<img
class="wp-image-123" src="http:://localhost/test.jpg">')
        ));

        wp_die();
    }
}


js/test.js
-------------------------------------------------------------------------------------------------------------
(function ($) {
    var test_url;

    if(typeof ajaxurl === "undefined") {
        test_url = cloudinary_ajax_test.ajax_url;
    } else {
        test_url = ajaxurl;
    }

    $.get(test_url, {action: "cloudinary_test"}, function (res) {
        console.log(res.html);
    });

})(jQuery);

**Comment by junaidbhura** [comment]
@baronleung Okay I understand the problem now, thank you. Let me see if I can find an elegant solution for this.

**Comment by baronleung** [comment]
sorry, I'm late checking my email. check DOING is ok, that's how I handled
it
