### ISSUE TITLE
Wrong comparison for valid URL

### ISSUE THREAD

**Issue by JimSeven** [junaidbhura/auto-cloudinary#16]
When validating the `$original_url` with `$this->_options['upload_url']` the comparison should be made on TURE or FALSE and not on 0.

**Change this in `inc/class-core.php` on line `86`:**
```
if (0 !== strpos($original_url, $this->_options['upload_url'])) {
     return $original_url;
}
```

**To this:**

```        
if (strpos($original_url, $this->_options['upload_url']) !== false) {
     return $original_url;
}
```

**Comment by junaidbhura** [comment]
Hey @JimSeven the idea is to look for the URL in the beginning of the string, therefore it looks for `0` rather than `boolean`:

http://php.net/manual/en/function.strpos.php
