### ISSUE TITLE
Progressive image loading paramater

### ISSUE THREAD

**Issue by delnolan** [junaidbhura/auto-cloudinary#20]
Hi @junaidbhura 

I wanted to pass the 'fl_progressive' paramater for image loading but the option wasn't available. 

I edited class-core.php to enable the option and then I just passed an empty string for 'progressive' in $args.

    public function build_transformation_slug( $args = array() ) {
		if ( empty( $args ) ) {
			return "";
		}
		$cloudinary_params = array(
			'angle'                => 'a',
			'aspect_ratio'         => 'ar',
			'background'           => 'b',
			'border'               => 'bo',
			'crop'                 => 'c',
			'color'                => 'co',
			'dpr'                  => 'dpr',
			'duration'             => 'du',
			'effect'               => 'e',
			'end_offset'           => 'eo',
			'flags'                => 'fl',
			'height'               => 'h',
			'overlay'              => 'l',
			'opacity'              => 'o',
			'quality'              => 'q',
			'radius'               => 'r',
			'start_offset'         => 'so',
			'named_transformation' => 't',
			'underlay'             => 'u',
			'video_codec'          => 'vc',
			'width'                => 'w',
			'x'                    => 'x',
			'y'                    => 'y',
			'zoom'                 => 'z',
			'audio_codec'          => 'ac',
			'audio_frequency'      => 'af',
			'bit_rate'             => 'br',
			'color_space'          => 'cs',
			'default_image'        => 'd',
			'delay'                => 'dl',
			'density'              => 'dn',
			'fetch_format'         => 'f',
			'gravity'              => 'g',
			'prefix'               => 'p',
			'page'                 => 'pg',
			'video_sampling'       => 'vs',
                        'progressive'       => 'fl_progressive',
		);

		$slug = array();
		foreach ( $args as $key => $value ) {
			if ( array_key_exists( $key, $cloudinary_params ) && $this->valid_value( $cloudinary_params[ $key ], $value ) && $key != 'progressive' ) {
				$slug[] = $cloudinary_params[ $key ] . '_' . $value;
			}
			if($key == 'progressive'){
                        $slug[] = $cloudinary_params[ $key ];
                   }
		}
		return implode( ',', $slug );
	}`

**Comment by junaidbhura** [comment]
Thanks for this @delnolan . This has now been added to the plugin.

Full release details here: https://github.com/junaidbhura/auto-cloudinary/releases/tag/1.2.0

**Comment by TheDancingCode** [comment]
Why not just pass `progressive` to the `flags` option?

**Comment by junaidbhura** [comment]
@TheDancingCode What benefit would you see from that approach?

**Comment by TheDancingCode** [comment]
I guess I don't understand why you provide a special option for a specific value of a transform parameter. The plugin already accepts the `flags` parameter, and `progressive` as its value.

In other words: `fl_progressive` **is** available, no need to map `progressive` to `fl_progressive`.

**Comment by junaidbhura** [comment]
@TheDancingCode Actually the flags parameter doesn't really do anything right now! It just adds `fl` to the URL. I've created a new issue for this:

https://github.com/junaidbhura/auto-cloudinary/issues/22

This will be part of the next release. Feel free to add any thoughts or concerns there!

**Comment by delnolan** [comment]
> Thanks for this @delnolan . This has now been added to the plugin.
> 
> Full release details here: https://github.com/junaidbhura/auto-cloudinary/releases/tag/1.2.0

@junaidbhura Nice!!!
