### ISSUE TITLE
Image block size will not change on Block editor

### ISSUE THREAD

**Issue by sukezane** [junaidbhura/auto-cloudinary#25]
**Describe the bug**
Cannot select image size on Image block after activated Auto Cloudinary plugin.

**To reproduce**
1. Go to Posts > Add New
2. Add Image block on editor.
3. Choose an image on Media Library
4. Select image size on Image block  settings, for example, choose ‘Medium’
![スクリーンショット 2019-09-04 14 57 27](https://user-images.githubusercontent.com/13991359/64229327-6f06ce00-cf24-11e9-84c5-b57a9011e97e.png)

**Expected behavior**
Image size will change and updated image size on actual post.
On Image Size dropdown list, all option value has different sources by each sizes.
![スクリーンショット 2019-09-04 15 00 12](https://user-images.githubusercontent.com/13991359/64229450-c1e08580-cf24-11e9-8370-b5e5b4bfba31.png)

**Actual behavior**
Image size will not change.
On Image Size dropdown list, all option value has same sources.
![スクリーンショット 2019-09-04 14 59 18](https://user-images.githubusercontent.com/13991359/64229462-c9079380-cf24-11e9-86e5-ea5496e990d4.png)

**Additional context**
- Wordpress 5.2
- PHP 7.3.0
- Nginx/1.15.7
- Auto Cloudinary Settings
[![Screenshot from Gyazo](https://gyazo.com/65c5c8a949bb96f69c42cb36f979f472/raw)](https://gyazo.com/65c5c8a949bb96f69c42cb36f979f472)

**Comment by junaidbhura** [comment]
Hey @sukezane thanks for this issue, and apologies for the delayed response. Let me take a deeper look at this and get back to you!

**Comment by junaidbhura** [comment]
@sukezane The plugin has now been updated with a fix!

**Comment by sukezane** [comment]
Thanks @junaidbhura ! 
But I think this issue is not fixed. 
Image Size dropdown lists' option value still has same image sources after activated newer version plugin.

**Comment by sukezane** [comment]
@junaidbhura 
When I added `return_false` to `cloudinary_filter_image_downsize` filter on my `functions.php`, it seems to be worked.
So I think this problem is occurred on `filter_image_downsize` function on  class-frontend.php.

In addition, when I looked into editor, I found image block's image is fetched from WP REST API on `/wp/v2/media/` endpoint. Since this endpoint used on editor, it might fix if this function is triggered only on actual post.

**Comment by junaidbhura** [comment]
@sukezane Thanks for letting me know. I've created a new branch with a fix: https://github.com/junaidbhura/auto-cloudinary/tree/editor-sizes-fix

Can you try this and let me know if it fixes the issue?

**Comment by sukezane** [comment]
@junaidbhura Thanks! It fixed.

**Comment by junaidbhura** [comment]
Thanks for confirming @sukezane ! I'll do a plugin release soon!
