### ISSUE TITLE
After configuring both Cloudinary and a page nothing happened

### ISSUE THREAD

**Issue by mkbctrl** [junaidbhura/auto-cloudinary#26]
Good evening!

I would like to ask, if you could have a look at my plugin config.

<img width="754" alt="Screenshot 2019-09-04 at 23 47 22" src="https://user-images.githubusercontent.com/10107362/64294162-7783f680-cf6e-11e9-8bb5-63720b9eccfb.png">
<img width="539" alt="Screenshot 2019-09-04 at 23 47 39" src="https://user-images.githubusercontent.com/10107362/64294163-7783f680-cf6e-11e9-8e8b-38712d799b35.png">

I did everything as described in the docs, but nothing happened. Did I miss anything, should I trigger that upload somehow?

I have currently the page blocked with Password Protect WordPress Lite, maybe this is the cause of such behavior?

**Comment by junaidbhura** [comment]
Hey @mkbctrl yes, the page needs to be publicly accessible by Cloudinary. So turning off the password protection will fix the issue.
