### ISSUE TITLE
Handle CNAME

### ISSUE THREAD

**Issue by Rahe** [junaidbhura/auto-cloudinary#30]
Hello,

the plugin doesn't allow to not enter a cloud-name, when using a CNAME this is not working.
So I had to use the url filter to replace the cloud-name in the url.

Have I missed something ?

Nicolas,

**Comment by junaidbhura** [comment]
Hi @Rahe 

I’m not sure I understand what you mean. Could you please give me an example?

**Comment by Rahe** [comment]
Hello,

In general you have the url : res.cloudinary.com/cloud-name/....
When I have the CNAME, the url will be like : images.mydomain.fr/....
The images are not pre-fixed with the cloud-name, and this is not possible to have no cloud-name.
So I had to remove the cloud-name from the url with your filter.

Is this possible to do so without the filtrer ?

Nicolas,

**Comment by junaidbhura** [comment]
Hey @Rahe ah okay. There's a field in the settings called "URLs". This is where you add custom domains / CNAMEs.

Can you try replacing `https://res.cloudinary.com` with `https://images.mydomain.fr` in there?

More info here: https://github.com/junaidbhura/auto-cloudinary/wiki/Setup#2-setting-up-wordpress

**Comment by junaidbhura** [comment]
Hey @Rahe I'm closing this issue out for now. Please feel free to comment here to continue this discussion.
