### ISSUE TITLE
v1.2.1 does not rewrite the to res.cloudinary.com url

### ISSUE THREAD

**Issue by marcomc** [junaidbhura/auto-cloudinary#31]
v1.2.2 doesn't show in the menu settings, so I switched to v1.2.1
v1.2.1 does not rewrite the to res.cloudinary.com url
when inspecting any page source all the img sources still point to the website url and to the cloudinary url
<img width="434" alt="Screenshot 2020-01-08 at 12 25 59" src="https://user-images.githubusercontent.com/1428680/71990452-27fe5180-3212-11ea-9c67-78d3cb08dbf2.png">

**Comment by junaidbhura** [comment]
Hey @marcomc Thanks for opening this issue. I've just updated the plugin to `1.2.3`. Can you try updating to see if it fixes your issues?

**Comment by marcomc** [comment]
sorry, but no changes, do you want me to check something specific?
could it be a hosting or CDN issue? I am using CloudFlare, but I have also disabled it for tests
<img width="639" alt="Screenshot 2020-01-09 at 00 43 50" src="https://user-images.githubusercontent.com/1428680/72036352-4d727600-3279-11ea-9474-e83fa28911d7.png">
<img width="447" alt="Screenshot 2020-01-09 at 00 43 31" src="https://user-images.githubusercontent.com/1428680/72036354-4e0b0c80-3279-11ea-9c75-68f2599f155e.png">

**Comment by junaidbhura** [comment]
Hmm @marcomc a couple of questions for you:

1. Does the admin page now show up?
1. Can you send me a link to a page I can see?

**Comment by marcomc** [comment]
I have found the issue:
- in the WP Settings->General WordPress Address (URL) and Site Address (URL) were set to http:// instead of https:// while the site was forced to run on https:// by the hosting configuration

when changing those settings to https:// the url rewrite to cloudinary url started working
Still there are a few images that are still served by the orginal site url instead of the cloudiary url...

**Comment by junaidbhura** [comment]
@marcomc Oh great that you've been able to figure it out! 👍

The only context in which it might not work is in the case of background images. This plugin only works to replace `<img>` tags.

Are the images you're seeing not using Cloudinary background images?

**Comment by junaidbhura** [comment]
Hey @marcomc I'm closing this issue out for now. Please feel free to continue this discussion here.
