### ISSUE TITLE
Image height is being returned as 9999px regardless

### ISSUE THREAD

**Issue by djmtype** [junaidbhura/auto-cloudinary#34]
I've been using this plugin with the default settings. I noticed that ALL large images, with varying proportions, are returning from Cloudinary with a wrong height of 9999 px. None of the original images that have been uploaded are even close to 9999 px tall either.

"Automatically use Cloudinary for all images" is checked.

**Comment by junaidbhura** [comment]
@djmtype Have you changed the default hard / soft cropping settings? Can you show me a screenshot of your settings?

**Comment by djmtype** [comment]
@junaidbhura  I don't believe so. Here's a screenshot [https://cloudup.com/ckZqpZ27RAk](https://cloudup.com/ckZqpZ27RAk)

**Comment by junaidbhura** [comment]
Hmm @djmtype you might want to check your thumbnail sizes in the theme. Especially the `size-zeus-blog-post`. I think this might be set at 9999 with a hard crop. You can just remove the hard crop option in that size and it should all be good. Something like:

`add_image_size( 'size-zeus-blog-post', 700, 9999, true );` <-- remove `true`

**Comment by djmtype** [comment]
@junaidbhura That sounds logical and true. I thought it was coincidental that other themes follow the same practice. So, I had tried the TwentyTwenty theme among others as well. It seems like common practice. I understand why they do it. So, I'll keep that in mind from now on.

TwentyTwenty: 
`set_post_thumbnail_size( 1200, 9999 );` 

`add_image_size( 'twentytwenty-fullscreen', 1980, 9999 );`

**Comment by junaidbhura** [comment]
Awesome, glad that this is now resolved! :)
