### ISSUE TITLE
Does it work with localhost?

### ISSUE THREAD

**Issue by ImKubass** [junaidbhura/auto-cloudinary#35]
Does it work with localhost? It seems not.

**Comment by junaidbhura** [comment]
Hi @ImKubass no, Cloudinary requires your images to be publicly available. So it wouldn't work locally, sorry about that!

**Comment by junaidbhura** [comment]
You could try falling back to some other plugin locally like this: https://github.com/junaidbhura/auto-cloudinary/wiki/Best-Practices
