### ISSUE TITLE
Headless Wordpress

### ISSUE THREAD

**Issue by djmtype** [junaidbhura/auto-cloudinary#37]
Logically, plugins don't work with a headless Wordpress setup. But, is there anyway to leave Cloudinary's CDN URL intact when exporting a Gridsome/Gatsby site? Using the auto content images option BTW.

**Comment by junaidbhura** [comment]
Hey @djmtype in addition to the `init` hook above, could you also add this?

```php
add_filter( 'cloudinary_allow_rest_api_call', '__return_true' );
```

**Comment by djmtype** [comment]
@junaidbhura Worked like a charm. Thank you very much!

**Comment by junaidbhura** [comment]
No worries @djmtype , happy to help :)

I think just to be safe, you could future-proof the code some more like so:

```php
if ( class_exists( '\JB\Cloudinary\Core' ) ) {
	add_action(
		'init',
		function () {
			\JB\Cloudinary\Core::get_instance()->setup();
			\JB\Cloudinary\Frontend::get_instance()->setup();
		}
	);

	add_filter( 'cloudinary_allow_rest_api_call', '__return_true' );
}
```

**Comment by junaidbhura** [comment]
That's right. Cheers!
