### ISSUE TITLE
tools cloudinary page is blank

### ISSUE THREAD

**Issue by lewisl** [junaidbhura/auto-cloudinary#4]
In the wordpress console, the tools cloudinary page is a big white blank square.  There are no fields to fill in for cloud name, etc.  So, you plugin is a no-op as a result. 

The official cloudinary plugin wouldn't even activate with a parse error over a claimed spurious open [.  I couldn't find it (looked like all braces were matching) so deleted the plugin and replaced with yours.

So far, cloudinary is dead to me.  They don't answer support requests with any speed except the automated acknowledgement email.

**Comment by junaidbhura** [comment]
Hey @lewisl based on everything you've mentioned, it sounds like there could be a problem with your WordPress installation. I'd recommend auditing your code, and looking into your logs to see what errors you're getting. You can try installing the official Cloudinary plugin and this one on a fresh WordPress install, and I'm sure you'll see that they both work.

I can't really help out with any Github issues without any details like an error or a screenshot of an error message. So I'm just closing this issue for the time being. You can feel free to comment here if you'd like.

**Comment by AndSheCodes2** [comment]
Not sure what happen but I reinstalled my server upgrading to php7. I was previously on 5 maybe that has something to do with it.

**Comment by junaidbhura** [comment]
Ah okay, great. Yes, this plugin requires at least PHP 5.6, as mentioned on the plugin's description:

<img width="991" alt="php-version" src="https://user-images.githubusercontent.com/2512525/41567057-b821efd2-73a1-11e8-9355-aea93ee511ed.png">
