### ISSUE TITLE
SRC attribute is set wrong

### ISSUE THREAD

**Issue by djmtype** [junaidbhura/auto-cloudinary#41]
I'm simply returning `the_post_thumbnail( 'large' )` on a single post. 
The proportions are correct but the SRC attribute for height is wrong. 

```
<img width="1024" height="1024" src="https://res.cloudinary.com/mtype-media/f_auto,fl_progressive:semi,q_90,w_1024,h_1024,c_fit/burpshaw/2021/05/photo-unsplash.jpg" class="attachment-large size-large wp-post-image" alt="" loading="lazy">
```

The height attribute should be 683px.

My settings: 

Default Hard Crop: fill
Default Soft Crop: fit

**Comment by junaidbhura** [comment]
Hi @djmtype thanks for creating this issue! I've created a new branch `fix/41-soft-crop-dimensions`. Do you think you could pull that down and test if it fixes your issue? Just want to be extra sure before releasing this. Here's the Pull Request for your reference: https://github.com/junaidbhura/auto-cloudinary/pull/44

Thanks!
