### ISSUE TITLE
Using the_post_thumbnail doesn't return a srcset of sizes

### ISSUE THREAD

**Issue by djmtype** [junaidbhura/auto-cloudinary#42]
Using something like `the_post_thumbnail( 'large' )` would normally return every image size smaller including large within a srcset. 

However, with this plugin enabled, it only returns the large image, nothing more. 

Do I need to set something else in Cloudinary or do I need to set up a function to handle this?

**Comment by junaidbhura** [comment]
Hi @djmtype thanks for creating this issue! As discussed in #41, I've created a branch which fixes this issue. Could you please test to see if it resolves your issue?
