### ISSUE TITLE
Allow named transformation

### ISSUE THREAD

**Issue by monecchi** [junaidbhura/auto-cloudinary#47]
Hi there. Thanks for this awesome plugin, it's a life saver!

As long as Cloudinary allows to create **named transformations**, I was wondering if would it be viable to include the functionality on a next plugin update? Here's their docs: https://cloudinary.com/documentation/named_transformations_tutorial, 

By hitting the image url as such https://res.cloudinary.com/demo/image/upload/t_global/Model_woman.jpg, where **global** is the transformation name, we could easily skip all the transformation arguments. Something as follows:

    $image_args = array(
        'transform' => array( 
            '_t' => 'site__header_image_wide__low',
        )
    );

**Comment by monecchi** [comment]
Sorry, just read the docs again and I found the **named_transformation** argument. I'll give it a try and see how that works. Thanks!

**Comment by junaidbhura** [comment]
thanks @monecchi - closing this issue!
