### ISSUE TITLE
My images breaks after I followed this guide

### ISSUE THREAD

**Issue by mauwiks** [junaidbhura/auto-cloudinary#6]
What should I do to fix this issue? Is there something wrong with my setting?

Cloudinary settings just default except to this screenshot: http://prntscr.com/koytx9 

The rest, I just followed your instruction.

Here's my site: https://mauwiks.com

**Comment by junaidbhura** [comment]
Hey @mauwiks,
I'm not sure what settings you have, so it's hard for me to comment.

If you've followed the instructions, it should all be working fine. I'm closing this issue for the moment, and will re-open it as soon as we know what actions to take. We can continue to have a discussion here.

Do you have other plugins which may conflict with this one?

**Comment by mauwiks** [comment]
It's okay now. Thank you! I think it's because of my caching plugin (LiteSpeed) not quite compatible with your plugin. But I was able to find another one that is much more compatible with it, WP Rocket. Thanks btw for your response.

**Comment by junaidbhura** [comment]
No worries, @mauwiks . Glad it's fixed! 😊
