### ISSUE TITLE
Two WP sites on one Cloudinary Account

### ISSUE THREAD

**Issue by mauwiks** [junaidbhura/auto-cloudinary#7]
Hi, thank you for this plugin!

BTW, I'd like to use my cloudinary account using your plugin for both of my WP sites. Should the URL be different?

Please see screenshot: http://prntscr.com/kvqayp

**Comment by junaidbhura** [comment]
Hey @mauwiks 

Yes, you can use the same Cloudinary account. Yes, the URLs should match what you are trying to reach.

I see you've created two auto mapping folders pointing to different URLs. It should be fine.
